### ISSUE TITLE
Not included in core

### ISSUE THREAD

**Issue by josephdadams** [bitfocus/companion-module-blackdiamondvideo-phantom800#2]
@KarstenTWolf This module is not in either the backport 1.4 branch or the master 2.0 branch. How is it coming along? Is it ready to be included?

**Comment by KarstenTWolf** [comment]
Hey,

Yes this module has been ready for a while. I had mentioned it in the
Slack, but it was right around the XL's launch so I think that message just
got buried.

-Karsten

**Comment by josephdadams** [comment]
Cool. I’ll get it added. Thanks!
